from __future__ import annotations

from enum import StrEnum

from app.schemas.common import ApiError


class ErrorCode(StrEnum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    FILE_REQUIRED = "FILE_REQUIRED"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    PIPELINE_RUN_NOT_FOUND = "PIPELINE_RUN_NOT_FOUND"

    # BE-3 document upload and text-processing errors.
    PDF_READ_FAILED = "PDF_READ_FAILED"
    TEXT_REQUIRED = "TEXT_REQUIRED"
    TEXT_TOO_SHORT = "TEXT_TOO_SHORT"
    TEXT_EXTRACTION_FAILED = "TEXT_EXTRACTION_FAILED"
    SECTION_DETECTION_FAILED = "SECTION_DETECTION_FAILED"
    FILE_STORAGE_FAILED = "FILE_STORAGE_FAILED"

    # BE-4 reference and DOI extraction errors.
    DOCUMENT_TEXT_NOT_FOUND = "DOCUMENT_TEXT_NOT_FOUND"
    REFERENCE_SECTION_NOT_FOUND = "REFERENCE_SECTION_NOT_FOUND"
    REFERENCE_EXTRACTION_FAILED = "REFERENCE_EXTRACTION_FAILED"
    REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND"
    DOI_MALFORMED = "DOI_MALFORMED"
    DEBUG_ENDPOINT_DISABLED = "DEBUG_ENDPOINT_DISABLED"
    REFERENCE_REEXTRACTION_BLOCKED = "REFERENCE_REEXTRACTION_BLOCKED"

    # BE-5 DOI metadata lookup errors.
    DOI_MISSING = "DOI_MISSING"
    DOI_LOOKUP_FAILED = "DOI_LOOKUP_FAILED"
    METADATA_UNAVAILABLE = "METADATA_UNAVAILABLE"
    METADATA_LOOKUP_TIMEOUT = "METADATA_LOOKUP_TIMEOUT"
    METADATA_SERVICE_UNAVAILABLE = "METADATA_SERVICE_UNAVAILABLE"

    # BE-6 claim and citation management errors.
    REFERENCES_NOT_FOUND = "REFERENCES_NOT_FOUND"
    CLAIM_EXTRACTION_FAILED = "CLAIM_EXTRACTION_FAILED"
    CLAIM_NOT_FOUND = "CLAIM_NOT_FOUND"
    CITATION_NOT_FOUND = "CITATION_NOT_FOUND"
    CLAIM_REFERENCE_LINK_NOT_FOUND = "CLAIM_REFERENCE_LINK_NOT_FOUND"
    REFERENCE_MAPPING_FAILED = "REFERENCE_MAPPING_FAILED"
    LOW_MAPPING_CONFIDENCE = "LOW_MAPPING_CONFIDENCE"
    GENAI_SERVICE_UNAVAILABLE = "GENAI_SERVICE_UNAVAILABLE"
    GENAI_INVALID_JSON = "GENAI_INVALID_JSON"
    GENAI_LOW_CONFIDENCE = "GENAI_LOW_CONFIDENCE"

    # BE-7 evidence package builder errors.
    EVIDENCE_PACKAGE_NOT_FOUND = "EVIDENCE_PACKAGE_NOT_FOUND"
    EVIDENCE_PACKAGE_BUILD_FAILED = "EVIDENCE_PACKAGE_BUILD_FAILED"
    SOURCE_EVIDENCE_UNAVAILABLE = "SOURCE_EVIDENCE_UNAVAILABLE"

    # BE-8 verification cache layer errors.
    CACHE_LOOKUP_FAILED = "CACHE_LOOKUP_FAILED"
    CACHE_DISABLED = "CACHE_DISABLED"
    CACHE_INDEX_NOT_FOUND = "CACHE_INDEX_NOT_FOUND"
    VERIFICATION_RESULT_NOT_FOUND = "VERIFICATION_RESULT_NOT_FOUND"
    SEMANTIC_CACHE_UNAVAILABLE = "SEMANTIC_CACHE_UNAVAILABLE"

    # BE-9 RAG/ML integration errors.
    RAG_SERVICE_UNAVAILABLE = "RAG_SERVICE_UNAVAILABLE"
    RAG_SERVICE_TIMEOUT = "RAG_SERVICE_TIMEOUT"
    RAG_INVALID_RESPONSE = "RAG_INVALID_RESPONSE"
    RAG_RETRIEVAL_FAILED = "RAG_RETRIEVAL_FAILED"
    NO_RELEVANT_EVIDENCE_FOUND = "NO_RELEVANT_EVIDENCE_FOUND"


    # BE-10 GenAI verification orchestration errors.
    PIPELINE_ALREADY_RUNNING = "PIPELINE_ALREADY_RUNNING"
    SAFETY_RULE_TRIGGERED = "SAFETY_RULE_TRIGGERED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"

    # BE-11 safety and confidence rules errors.
    SAFETY_CHECK_NOT_FOUND = "SAFETY_CHECK_NOT_FOUND"
    SAFETY_EVALUATION_FAILED = "SAFETY_EVALUATION_FAILED"
    SAFETY_POLICY_INVALID = "SAFETY_POLICY_INVALID"
    CONFIDENCE_THRESHOLD_FAILED = "CONFIDENCE_THRESHOLD_FAILED"
    LOW_SIMILARITY = "LOW_SIMILARITY"
    GENAI_RAG_CONFLICT = "GENAI_RAG_CONFLICT"
    EVIDENCE_USED_MISMATCH = "EVIDENCE_USED_MISMATCH"
    DOI_INVALID = "DOI_INVALID"


class AppException(Exception):
    """Known application exception returned using the standard API wrapper."""

    def __init__(
        self,
        *,
        status_code: int = 400,
        code: ErrorCode = ErrorCode.INTERNAL_SERVER_ERROR,
        detail: str,
        field: str | None = None,
        message: str | None = None,
    ) -> None:
        self.status_code = status_code
        self.error = ApiError(code=code.value, field=field, detail=detail)
        self.message = message or detail
        super().__init__(detail)
